# Generated by Django 4.0.2 on 2022-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_specie', models.CharField(max_length=100, verbose_name='Add New Specie')),
            ],
        ),
        migrations.RemoveField(
            model_name='species',
            name='new_specie',
        ),
    ]
